### ISSUE TITLE
Bug: Date Not Correctly Posted

### ISSUE THREAD

**Issue by luigar** [JuditKaramazov/TakeYouThere#17]
### Describe the bug

Adding PINS with a date are showing 1 day before the actual date , example 2024-06-12 is posting as 2024-06-11 same with other dates. 

### Steps to reproduce

1. Add location in places.ts
2. Refresh server
3. View Map Pin

### Do you have any screenshots?

![image (8)](https://github.com/JuditKaramazov/TakeYouThere/assets/1890179/c997c4b7-3cc1-480e-b206-c94c971f0bfd)
![image (7)](https://github.com/JuditKaramazov/TakeYouThere/assets/1890179/4c2ec297-3d58-4480-aa51-de80b5fa8d38)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [X] I agree to follow this project's Contribution Docs

**Comment by JuditKaramazov** [comment]
Welcome, luigar!

First of all, excuse me for my belated response; it's been a complicated time!
After having a look at the code (as well as my pictures and dates), I must admit I never encountered the problem you're experiencing. That's why, after thinking of it, I concluded that it might be related to different time zones, as I kept in mind Europe/Madrid (Barcelona, to be more specific), but I didn't consider other options.

In all honesty, the `getRelativeTimeString` function might be potentially problematic due to the way it handles dates and times - especially when it comes to different time zones. Could you please give the following alternative a try and tell me if it solves your problem?

```typescript
export const getRelativeTimeString = (date: string) => {
  const parsedDate = DateTime.fromISO(date, { zone: 'utc' }); // You'll have to explicitly set the zone here.
  const relativeTime = parsedDate.toRelative();

  // Formatting the date in a specific time zone might help, too. Let's say 'Europe/London' here, for instance.
  const formattedDate = parsedDate.setZone('Europe/London').toLocaleString(DateTime.DATETIME_MED);

  return `${relativeTime} (${formattedDate})`;
}
```

Perhaps we should explicitly handle time zones when parsing and formatting dates for more consistent behavior.
Let me know if it works for you; if that's not the case, we'll look for another solution!
Best wishes,


Judit
